# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
