# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_email_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
